ACK = 'ack'
MAX_DATA = 'max_data'
MAX_STREAM_DATA = 'max_stream_data'
STREAM = 'stream'
DATAGRAM = 'datagram'
HANDSHAKE_DONE = 'handshake_done'
STOP_SENDING = 'stop_sending'
RESET_STREAM = 'reset_stream'
